### ISSUE TITLE
Without seed the map is always the same

### ISSUE THREAD

**Issue by HyperionCoding** [Moppa5/pirkanmaan-valloitus#9]
**Description**
If the players do not input any seed, the map will always be the same. When using a seed this is of course still a wanted feature.

**Solution**
Check if the seed is empty and use some system variable as a seed, such as the time, or use Qt's builtin random generator features.

**Comment by Moppa5** [comment]
I personally don't think that this is a bug. It's not said anywhere explicitly that the map should be different every time hence there's the seed for having a different map. However, this can be a feature and relatively easily implemented if really wanted.
